# Generated by Django 5.1.1 on 2024-09-26 07:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('break_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_break_time_taken',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AlterField(
            model_name='breaksettings',
            name='break_slots_per_hour',
            field=models.IntegerField(default=5),
        ),
    ]
