# Generated by Django 5.1.1 on 2024-09-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('break_management', '0002_customuser_total_break_time_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='total_break_time_taken',
            field=models.DurationField(default=0),
        ),
    ]
