# Generated by Django 5.1.1 on 2024-09-27 12:36

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('break_management', '0003_alter_customuser_total_break_time_taken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakslot',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='total_break_time_taken',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
